import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Header from "@/components/custom/header";
import { Toaster } from "sonner";
import ReactQueryProvider from "@/providers/ReactQueryProvider";
import StoreProvider from "@/providers/StoreProvider";
import TokenRefresherProvider from "@/providers/TokenRefresherProvider";

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-manrope antialiased",
          manrope.variable
        )}
      >
        <StoreProvider>
          <ReactQueryProvider>
            <TokenRefresherProvider>
              <Header />
              <main>{children}</main>
              <Toaster richColors position="top-center" />
            </TokenRefresherProvider>
          </ReactQueryProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
